#!/bin/bash
xmverilog \
		  +xm64bit \
		  +access+r \
        -y ./ \
        -y ./../channel \
        -y ./../code \
	+libext+.v+.sv+ \
	+uncdir+./ \
	+uncdir+./../channel \
	+uncdir+./../code \
        ./tb_top.sv

