#!/bin/tcsh

#set p_clk = '100'
#set fm_jtt_db_g = '-80'
#set pm_jtt_db_g = '-125'

#set ptrn_sel_g = '0'
#set dlf_init_code_g = '59' 
#set ctle_ac_gain='0'
#set ctle_dc_gain_g = (0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15)
#set DELAY = (0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21)
set DELAY = (2 3)
#set ctle_weight_g = '0001_0001_1000_1000_0000_0000_1000_0100_0001_0100_0000_0000_1000_0010_0001_0010'


#set tstop_g = '6000'
#set tstart_g = '4000'

#\rm -f ./00_result/*.vec
#\rm -f ./00_result/*.csv

#	foreach tstop ($tstop_g)
#		foreach tstart ($tstart_g)
#			foreach fm_jtt_db ($fm_jtt_db_g)
#				foreach pm_jtt_db ($pm_jtt_db_g)
					set i = 1 
#					echo ctle_dc_gain hist 18dB_ch >! ./00_result/190814_BB_DC_18dB/5s_bb_pm_ctle_DC_ch_18dB_sweep\_$tstop\_phase_pm\_$pm_jtt_db\_result.csv
						while($i < 3) 
#							set ctle_dc_gain_value = $ctle_dc_gain_g[$i]	
#							set DELAY = $DELAY[$i]
							echo "initial begin" >! ./reg.py
#							echo "ctle_code <= 4'd"$ctle_dc_gain_value";" >> ./reg.v
#							echo "ac_gain_code <= 4'd"$ctle_ac_gain";" >> ./reg.v
#							echo "ptrn_sel <= 2'b0"$ptrn_sel_g";" >> ./reg.v
#							echo "dlf_init_code <= 10'd"$dlf_init_code_g";" >> ./reg.v
							echo "end" >> ./reg.py
					

#							echo parameter real p_clk = $p_clk";" >! ./param.v
							set data_in_k1 = './data/PAM4_real/w_AGC/23dB/data_in_'$DELAY[$i]'.txt'
							set data_in_k2 = './data/PAM4_real/w_AGC/17dB/data_in_'$DELAY[$i]'.txt'
#							set data_in_k3 = './data/PAM4_real/w_AGC/10dB/data_in_'$DELAY[$i]'.txt'
#							set data_in_k4 = './data/PAM4_real/10dB/data_in_'$DELAY[$i]'.txt'
							set data_out_k1 = './data/PAM4_real/w_AGC/23dB/data_out_'$DELAY[$i]'.txt'
							set data_out_k2 = './data/PAM4_real/w_AGC/17dB/data_out_'$DELAY[$i]'.txt'
#							set data_out_k3 = './data/PAM4_real/w_AGC/10dB/data_out_'$DELAY[$i]'.txt'
#							set data_out_k4 = './data/PAM4_real/10dB/data_out_'$DELAY[$i]'.txt'
#							set data_in_k_test = './data/PAM4_real/27dB/data_in_'$DELAY[$i]'.txt'
#							set data_out_k_test = './data/PAM4_real/27dB/data_out_'$DELAY[$i]'.txt'
							echo data_in1 = "'"$data_in_k1"'" >! ./param.py
							echo data_in2 = "'"$data_in_k2"'" >> ./param.py
#							echo data_in3 = "'"$data_in_k3"'" >> ./param.py
#							echo data_in4 = "'"$data_in_k4"'" >> ./param.py
							echo data_out1 = "'"$data_out_k1"'" >> ./param.py
							echo data_out2 = "'"$data_out_k2"'" >> ./param.py
#							echo data_out3 = "'"$data_out_k3"'" >> ./param.py
#							echo data_out4 = "'"$data_out_k4"'" >> ./param.py
#							echo data_in_test = "'"$data_in_k_test"'" >> ./param_t.py
#							echo data_out_test = "'"$data_out_k_test"'" >> ./param_t.py
#							echo parameter real fm_jtt_db = $fm_jtt_db";" >> ./param.py
#							echo parameter real pm_jtt_db = $pm_jtt_db";" >> ./param.py
#							echo parameter real tstop = $tstop";" >> ./param.py
#							echo parameter real tstart = $tstop";" >> ./param.py
							python top_ff.py
							mv ./result/ML_EQ_weight ./result/ML_EQ_weight_$DELAY[$i]
#							./hist_de.py
#							set hist = `cat ./00_result/hist.vec`
#							echo $ctle_dc_gain_value, $hist >> ./00_result/190814_BB_DC_18dB/5s_bb_pm_ctle_DC_ch_18dB_sweep\_$tstop\_phase_pm\_$pm_jtt_db\_result.csv
							@ i++
						end
					end		
#				end
#			end
#		end
#	end

